services:
  suivi-colis-iutv:
    build:
      context: .
      dockerfile: configDocker/docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app/index.php:${APP_DIRECTORY}/index.php
    container_name: suivi-colis-container