services:
  suivi-colis-iutv:
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: configDocker/docker/Dockerfile.ubuntu
    ports:
      - "8080:80"
    volumes:
      - ./app/index.php:${APP_DIRECTORY}/index.php
    container_name: suivi-colis-container